# NetherPerms configuration
# default-group: The group assigned to players on first join
# track: optional ordered list of groups for promotions (not yet used in MVP)
default-group: default

# Storage backend: yaml or sqlite
storage: sqlite
# SQLite database file (used when storage=sqlite)
# Use plugin_data/... to store under the server data folder (proper-cased)
sqlite-file: plugin_data/NetherPerms/netherperms.sqlite

# Note: when storage=sqlite, users.yml and groups.yml are ignored and not created.

# If true, remove OP from players when applying permissions so explicit false values can take effect.
# Players in any of the listed bypass groups will keep OP (useful for owners).
strip-op-on-apply: true
bypass-groups:
  - admin

# Permission evaluation behavior
# If true (default), an explicit false will block later allows (deny has precedence).
# If false, later allows can override earlier denies (useful when higher groups should override lower-group denies).
deny-precedence: true

# Context notes:
# You can use contexts on permissions like:
#   pocketmine.command.gamemode.self:
#     world=world,gamemode=creative: true
#     world=world,gamemode=survival: false
# Separators ',' or ';' are both accepted between key=value pairs.

primary-group-calculation: stored #stored or parents-by-weight 